name: game_frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  extended_image: ^8.2.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.1
  kakao_flutter_sdk_user: ^1.9.2
  localstorage: ^5.0.0
  flutter_web_auth: ^0.5.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  web_socket_channel: ^2.1.0
  stomp_dart_client: ^2.0.0
  uuid: ^4.4.0
  

flutter:
  uses-material-design: true
  fonts:
    - family: Galmuri7
      fonts:
        - asset: fonts/Galmuri7.ttf
    - family: Press Start 2P
      fonts:
        - asset: fonts/Press Start 2P.ttf